### ISSUE TITLE
Not able to make the executable

### ISSUE THREAD

**Issue by harsh-agarwal** [higerra/ridi_imu#1]
After installing all the dependencies I get the following output:

https://gist.github.com/harsh-agarwal/355752b0393911460126f1a5fcb1474e 

I guess it's not able to find the definition of some operator in a particular header file. I am not sure. I am a beginner. Would be glad if you could help :) 

Thanks!

**Comment by harsh-agarwal** [comment]
Thinking it to be a configuration issue, I tried to rebuild everything from scratch..yet I am getting the same error. Any help would be appreciated :)

**Comment by higerra** [comment]
Hi, Harsh,
Seems most errors are about operator overloading. What version of Eigen and Ceres solver are you using?

**Comment by harsh-agarwal** [comment]
Eigen 3.2.92
Ceres cloned from here: git clone https://ceres-solver.googlesource.com/ceres-solver
I was getting similar errors after building with Ceres 1.14 so I thought it might be because of I did not have the latest version of it. So cloned directly from the main repo.

**Comment by higerra** [comment]
Thanks! I guess the problem should be the Eigen version. You can try using Eigen > 3.3.
I will check which version I used once I get the chance to connect to my lab computer.

**Comment by higerra** [comment]
And don't forget to recompile Ceres from scratch after upgrading Eigen.

**Comment by harsh-agarwal** [comment]
Do I need to download that manually?

Can you please tell me how to remove the present version completely, and download the latest version...

 And Thanks for the ceres note. I need to remember that!

**Comment by higerra** [comment]
If you are using Linux / Mac:
1. Delete previous version of Eigen. Eigen is a header only library. Simply remove /usr/local/include/eigen3 folder. Download the newer version, follow the installation instruction.
2. If you compile Ceres from source, simply delete build folder and build it again with the new Eigen. When you type "make install", newly built Ceres will overwrite the older one.

I'm not familiar with Windows. But it should be something similar.

**Comment by harsh-agarwal** [comment]
I am using Linux. That should work :) 

I will just try it and update you about the same!

**Comment by harsh-agarwal** [comment]
this worked! Thanks :)
