### ISSUE TITLE
Dataset: How exactly has it been used?

### ISSUE THREAD

**Issue by harsh-agarwal** [higerra/ridi_imu#4]
Hi,

As I am replicating your results, I would like to use the exact same data the way you used it in your research. 

Does the data link in the readme has all the 100 min of data that you had recorded? Could you please tell which sequences were used for training and which were used for testing? 

If that is only the train data...could you please share your test data as well? 

Thanks!

**Comment by higerra** [comment]
Hi, Harsh,
I attached four list files that can help you reproduce the result:
"list_train_publish_v2.txt" is the list of training sequences.
"list_test_publish_v2.txt" is the list of testing sequences (used to report the testing error).
"list_submission.txt" is the list of sequences in Table 2. The line number corresponds to the sequence number. For example, the second line corresponds to "T2" in the table.
"list_crosssubject.txt" is the list of sequences used in the cross subject experiment in Table 4. 

[list_crosssubject.txt](https://github.com/higerra/ridi_imu/files/2351079/list_crosssubject.txt)
[list_submission.txt](https://github.com/higerra/ridi_imu/files/2351080/list_submission.txt)
[list_test_publish_v2.txt](https://github.com/higerra/ridi_imu/files/2351081/list_test_publish_v2.txt)
[list_train_publish_v2.txt](https://github.com/higerra/ridi_imu/files/2351082/list_train_publish_v2.txt)

**Comment by harsh-agarwal** [comment]
Thank you so much for your response! I guess you have updated the data set, my bad, I did not see!

I would try getting the results and get back to you if any problems come up :) 

Thanks!

**Comment by higerra** [comment]
Hi, Harsh,
I just realized that the origin link to the dataset is outdated. Please re-download the dataset from:
https://wustl.box.com/s/6lzfkaw00w76f8dmu0axax7441xcrzd9

**Comment by harsh-agarwal** [comment]
Is this the link that you have on the public website? That's the project page...

**Comment by higerra** [comment]
Yes, but I updated it yesterday. So if you downloaded before yesterday, you will need to re-download. Otherwise, the dataset name and the list files won't match.

**Comment by harsh-agarwal** [comment]
Cool!

**Comment by harsh-agarwal** [comment]
Hi,

The test list has some names like hang_handheld_test1 which aren't there in the directory. Could you tell how to get those folders? Thanks! 

Cheers
Harsh

**Comment by higerra** [comment]
Sorry, I forgot to put these folders. Just uploaded a new version. You can download it from:
https://wustl.box.com/s/6lzfkaw00w76f8dmu0axax7441xcrzd9
