### ISSUE TITLE
implementing my own data

### ISSUE THREAD

**Issue by Ador2** [higerra/ridi_imu#8]
when i run regression.py this error comes up after it says "all done":
`Traceback (most recent call last):
  File "regression_cascade.py", line 467, in <module>
    model.train(feature_train, label_train.astype(np.int32), responses_train)
  File "regression_cascade.py", line 177, in train
    target_in_class[:, chn].astype(np.float32))
cv2.error: OpenCV(4.0.0) /io/opencv/modules/ml/src/svm.cpp:1404: error: (-215:Assertion failed) sv_count != 0 in function 'do_train'`

note: i didn't use a camera

**Comment by higerra** [comment]
The error indicates that the there is no supporting vectors for a specific label. This may be caused by empty categories in the training set. Make sure that you have samples for each class.

**Comment by yywang0225** [comment]
I have met the question, too. I wonder how could I solve this problem? BTW, I use a non-tango phone, the collected position information is empty (pose.txt), but I found in the training process, the position is used to generate responses_train in training_data process. When I try to implement my own data, the responses_train is always being zero. Very appreciate for your help and reply

**Comment by higerra** [comment]
To be clear, are you collecting training data with a non-tango phone? It won't work unless you have other ways to obtain ground-truth device poses. "pose.txt" will always be generated and preprocessed, with or without Tango, for ease of implementation.

If you train with all zero ground-truth positions, you are likely to trigger this "sv_count != 0" assert.

If you are doing research on this, I recommend you try the following:
https://github.com/higerra/ridi_imu/issues/10#issuecomment-495007008
