### ISSUE TITLE
online algorithm

### ISSUE THREAD

**Issue by Ador2** [higerra/ridi_imu#9]
when I'm wrapping the c++ code in python it generates error related to namespace (which is ridi),
i was wrapping model_wrapper for that in speed regression, how can i correct those errors?
or is there a specific way to do the live algorithm?

**Comment by higerra** [comment]
Hi, Ador2,
Sorry for the late reply. I don't know too much about python wrapper. But as a suggestion, I strongly recommend you to check out our newer work on the topic, which is in every aspect far better than RIDI:
RoNIN: Robust Neural Inertial Navigation
http://ronin.cs.sfu.ca/

The code is under releasing, but I believe you can get early access by contacting another first author:
Sachini Herath: sachini_herath@sfu.ca

The new algorithm uses LSTM, which is online in nature and can be deployed to mobile device easily.

Hope this is helpful.

**Comment by Ador2** [comment]
thank you very much @higerra
